import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  fields: [
    defineField({
      name: 'hero',
      type: 'object',
      title: 'Hero',
      fields: [
        defineField({name: 'indexLabel', type: 'string', title: 'Index label (e.g. /INDEX 2026)'}),
        defineField({name: 'version', type: 'string', title: 'Version label (e.g. /v 4.2)'}),
        defineField({name: 'coordsLat', type: 'string', title: 'Coords (latitude line)'}),
        defineField({name: 'coordsLon', type: 'string', title: 'Coords (longitude line)'}),
        defineField({name: 'heading', type: 'string', title: 'Heading line 1'}),
        defineField({name: 'headingLine2', type: 'string', title: 'Heading line 2'}),
        defineField({name: 'headingEmphasis', type: 'string', title: 'Heading emphasis word (italicised)'}),
        defineField({name: 'headingTail', type: 'string', title: 'Heading tail (after emphasis on final line)'}),
        defineField({name: 'tagline', type: 'text', title: 'Tagline (allows line breaks)', rows: 2}),
        defineField({name: 'credential1', type: 'string', title: 'Credential line 1'}),
        defineField({name: 'credential2', type: 'string', title: 'Credential line 2'}),
        defineField({name: 'statusLine1', type: 'string', title: 'Status line 1 (e.g. NOW — Booking Q3 2026)'}),
        defineField({name: 'statusLine2', type: 'string', title: 'Status line 2 (e.g. STATUS — 2 slots open)'}),
        defineField({name: 'statusLine3', type: 'string', title: 'Status line 3 (e.g. NEXT — project ships date)'}),
        defineField({name: 'nowLabel', type: 'string', title: 'NOW label (e.g. NOW)'}),
        defineField({name: 'nowValue', type: 'string', title: 'NOW value (e.g. Booking Q3 2026)'}),
        defineField({name: 'statusLabel', type: 'string', title: 'STATUS label'}),
        defineField({name: 'statusValue', type: 'string', title: 'STATUS value (e.g. 2 slots open)'}),
        defineField({name: 'nextLabel', type: 'string', title: 'NEXT label'}),
        defineField({name: 'nextValue', type: 'string', title: 'NEXT value (e.g. Yujo Izakaya ships 14 May)'}),
        defineField({name: 'ctaPrimary', type: 'ctaButton', title: 'Primary CTA'}),
        defineField({name: 'ctaSecondary', type: 'ctaButton', title: 'Secondary CTA'}),
        defineField({name: 'marqueeItems', type: 'array', title: 'Marquee items', of: [{type: 'string'}]}),
      ],
    }),
    defineField({
      name: 'workSection',
      type: 'object',
      title: 'Work Section',
      fields: [
        defineField({name: 'eyebrow', type: 'string', title: 'Eyebrow (e.g. /SECTION 01 — WORK)'}),
        defineField({name: 'heading', type: 'string', title: 'Heading line 1'}),
        defineField({name: 'headingEmphasis', type: 'string', title: 'Heading emphasis (line 2, italicised)'}),
        defineField({name: 'headingTail', type: 'string', title: 'Heading tail (rest of line 2)'}),
        defineField({name: 'indexLink', type: 'ctaButton', title: 'Index link (mobile bottom)'}),
      ],
    }),
    defineField({
      name: 'studioSection',
      type: 'object',
      title: 'Studio Section',
      fields: [
        defineField({name: 'eyebrow', type: 'string', title: 'Eyebrow'}),
        defineField({name: 'body', type: 'text', title: 'Body copy', rows: 4}),
        defineField({name: 'bodyEmphasis', type: 'string', title: 'Body emphasis (italicised tail)'}),
        defineField({
          name: 'stats',
          type: 'array',
          title: 'Stats',
          of: [{type: 'object', fields: [
            {name: 'label', type: 'string', title: 'Label'},
            {name: 'value', type: 'string', title: 'Value'},
          ]}],
        }),
        defineField({
          name: 'capabilities',
          type: 'array',
          title: 'Capabilities',
          of: [{type: 'stackCategory'}],
        }),
      ],
    }),
    defineField({
      name: 'startSection',
      type: 'object',
      title: 'Start Section',
      fields: [
        defineField({name: 'eyebrow', type: 'string', title: 'Eyebrow'}),
        defineField({name: 'heading', type: 'string', title: 'Heading line 1'}),
        defineField({name: 'headingEmphasis', type: 'string', title: 'Heading emphasis (italicised)'}),
        defineField({name: 'scopeOptions', type: 'array', title: 'Scope options', of: [{type: 'string'}]}),
        defineField({name: 'budgetOptions', type: 'array', title: 'Budget options', of: [{type: 'string'}]}),
      ],
    }),
    defineField({
      name: 'featuredProjects',
      title: 'Featured Projects',
      type: 'array',
      description: 'Drag to reorder. These projects appear on the homepage work grid.',
      of: [
        {
          type: 'reference',
          to: [{type: 'project'}],
        },
      ],
      validation: (Rule) => Rule.unique(),
    }),
  ],
  preview: {prepare: () => ({title: 'Home Page'})},
})
